[package]
name = "xlib"
version = "0.0.1"
authors = ["Daggerbot <daggerbot@gmail.com>"]
description = "Xlib binding for Rust."
license = "BSD-2-Clause"
repository = "https://github.com/Daggerbot/xlib.rs.git"
